version: '3'

networks:
  my-net:

services:
  mongo-database:
    image: "mongo:latest"
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    networks:
      - my-net
  server:
    build: ./server
    ports:
      - 1234:1234
    environment:
      - MONGO_URL=mongodb://mongo-database:27017/cities-docker
      - API_KEY=9bc4bbc08690c88e0caf8914e5b99717
    depends_on:
      - mongo-database
    networks:
      - my-net
  client:
    build: ./client
    ports:
      - 8889:80
    networks:
      - my-net